Update dependency org.springframework.boot:spring-boot-starter-web to v2.3.1.RELEASE (#684)
This PR contains the following updates:

| Package | Update | Change |
|---|---|---|
| [org.springframework.boot:spring-boot-starter-web](https://spring.io/projects/spring-boot) ([source](https://togithub.com/spring-projects/spring-boot)) | patch | `2.3.0.RELEASE` -> `2.3.1.RELEASE` |

---

### Release Notes

<details>
<summary>spring-projects/spring-boot</summary>

### [`v2.3.1.RELEASE`](https://togithub.com/spring-projects/spring-boot/releases/v2.3.1.RELEASE)

[Compare Source](https://togithub.com/spring-projects/spring-boot/compare/v2.3.0.RELEASE...v2.3.1.RELEASE)

#### :star: New Features

-   Provide dependency management for Oracle?s JDBC driver under new com.oracle.database Maven coordinates [#&#8203;21663](https://togithub.com/spring-projects/spring-boot/issues/21663)
-   Spring Cloud's CachedRandomPropertySource is not adapted correctly [#&#8203;21660](https://togithub.com/spring-projects/spring-boot/issues/21660)
-   Restrict use of custom YAML types [#&#8203;21598](https://togithub.com/spring-projects/spring-boot/issues/21598)
-   Improve failure analysis of NoSuchMethodErrors to show where superclasses were loaded from [#&#8203;21587](https://togithub.com/spring-projects/spring-boot/issues/21587)
-   Provide better error message if Docker is not running [#&#8203;21554](https://togithub.com/spring-projects/spring-boot/issues/21554)
-   Optimize SystemEnvironmentPropertyMapper [#&#8203;21523](https://togithub.com/spring-projects/spring-boot/pull/21523)
-   Provide better diagnostics when building an OCI image fails due to a 500 response from Docker [#&#8203;21515](https://togithub.com/spring-projects/spring-boot/issues/21515)
-   Consider configuring UrlPathHelper with alwaysUseFullPath=true  [#&#8203;21499](https://togithub.com/spring-projects/spring-boot/issues/21499)
-   Support user info in Elasticsearch URIs [#&#8203;21381](https://togithub.com/spring-projects/spring-boot/pull/21381)
-   Welcome page support in Spring WebFlux [#&#8203;9785](https://togithub.com/spring-projects/spring-boot/issues/9785)

#### :beetle: Bug Fixes

-   Default log levels are inconsistent between log4J2 and logback [#&#8203;21882](https://togithub.com/spring-projects/spring-boot/issues/21882)
-   Actuator 'loggers' endpoint does not return all loggers for log4j [#&#8203;21880](https://togithub.com/spring-projects/spring-boot/issues/21880)
-   Not able to use digest in 'builder' reference [#&#8203;21879](https://togithub.com/spring-projects/spring-boot/issues/21879)
-   Different actuator management server port changes response on errors [#&#8203;21875](https://togithub.com/spring-projects/spring-boot/issues/21875)
-   WebMvcTest does not use the auto-configured ordering for Spring Security's filter [#&#8203;21837](https://togithub.com/spring-projects/spring-boot/issues/21837)
-   Configuring server.\* properties in a child context has no effect in Spring Boot 2.3 [#&#8203;21789](https://togithub.com/spring-projects/spring-boot/issues/21789)
-   STOMP does not work with lazy initialization [#&#8203;21786](https://togithub.com/spring-projects/spring-boot/issues/21786)
-   Auto-Configuration for Cassandra does not back off if a custom ReactiveSessionFactory is defined  [#&#8203;21769](https://togithub.com/spring-projects/spring-boot/pull/21769)
-   Spring Boot CLI adds classes from current directory to the classpath on Unix-like platforms [#&#8203;21755](https://togithub.com/spring-projects/spring-boot/issues/21755)
-   Unpacked Spring Boot applications don't show version on startup [#&#8203;21705](https://togithub.com/spring-projects/spring-boot/issues/21705)
-   Fix BasicErrorController to use binding error cfg [#&#8203;21702](https://togithub.com/spring-projects/spring-boot/pull/21702)
-   UnsupportedOperationException is thrown from war when shutting down Tomcat [#&#8203;21684](https://togithub.com/spring-projects/spring-boot/issues/21684)
-   Docker calls may hang forever [#&#8203;21672](https://togithub.com/spring-projects/spring-boot/issues/21672)
-   SpringConfigurationPropertySource incorrectly returns ABSENT for sub properties [#&#8203;21655](https://togithub.com/spring-projects/spring-boot/issues/21655)
-   Management security configuration does not back off when SAML is configured [#&#8203;21642](https://togithub.com/spring-projects/spring-boot/issues/21642)
-   Dependency management for Kafka 2.5 on nonexistent org.apache.kafka:kafka_2.11:2.5.0 [#&#8203;21589](https://togithub.com/spring-projects/spring-boot/issues/21589)
-   NoSuchBeanDefinitionException for org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry when trying to publish AvailabilityChangeEvent during context close processing after refresh failure [#&#8203;21588](https://togithub.com/spring-projects/spring-boot/issues/21588)
-   Connection and read timeouts are no longer mapped for NewRelic [#&#8203;21578](https://togithub.com/spring-projects/spring-boot/issues/21578)
-   PropertiesLauncher cannot load a resource in jar via URL [#&#8203;21575](https://togithub.com/spring-projects/spring-boot/issues/21575)
-   Period conversion support should not be public [#&#8203;21574](https://togithub.com/spring-projects/spring-boot/issues/21574)
-   Reintroduce RestClientBuilderCustomizer in deprecated form [#&#8203;21572](https://togithub.com/spring-projects/spring-boot/issues/21572)
-   URI tag for WebMvc and WebFlux metrics is empty, rather than "root", when the path pattern is empty [#&#8203;21560](https://togithub.com/spring-projects/spring-boot/issues/21560)
-   Maven plugin help is missing [#&#8203;21556](https://togithub.com/spring-projects/spring-boot/issues/21556)
-   productionRuntimeClasspath fails to resolve multiplatform dependency variants  [#&#8203;21549](https://togithub.com/spring-projects/spring-boot/issues/21549)
-   Pulling CNB run image fails when no tag is provided in image name [#&#8203;21532](https://togithub.com/spring-projects/spring-boot/issues/21532)
-   ServletWebServerApplicationContext uses a logger for ContextLoader for some of its logging [#&#8203;21522](https://togithub.com/spring-projects/spring-boot/issues/21522)
-   Dependency version for org.apache.commons:commons-compress is missing from spring-boot-gradle-plugin's pom [#&#8203;21518](https://togithub.com/spring-projects/spring-boot/issues/21518)
-   Scope of some dependencies has changed from compile to runtime [#&#8203;21507](https://togithub.com/spring-projects/spring-boot/issues/21507)
-   Password-based authentication with Cassandra does not work with Spring Boot 2.3.0 [#&#8203;21487](https://togithub.com/spring-projects/spring-boot/issues/21487)
-   Order of map property in application yaml is no longer preserved [#&#8203;21470](https://togithub.com/spring-projects/spring-boot/issues/21470)
-   Fix MustacheEnvironmentCollector to not ignore native fetcher [#&#8203;21060](https://togithub.com/spring-projects/spring-boot/pull/21060)
-   [@&#8203;SpringBootTest](https://togithub.com/SpringBootTest) not picking [@&#8203;Named](https://togithub.com/Named) classes with a non-public constructor [#&#8203;20929](https://togithub.com/spring-projects/spring-boot/pull/20929)

#### :notebook_with_decorative_cover: Documentation

-   Document using system properties in gradle plugin docs [#&#8203;21798](https://togithub.com/spring-projects/spring-boot/issues/21798)
-   spring.config.name is not formatted as an environment variable in multi-page reference documentation [#&#8203;21794](https://togithub.com/spring-projects/spring-boot/issues/21794)
-   Clarify that configuring a custom health HTTP status mapping replaces the default mappings [#&#8203;21762](https://togithub.com/spring-projects/spring-boot/issues/21762)
-   Document the difference in dispatch type and the effect on the security filter caused by the error page filter when deployed to a standalone container [#&#8203;21760](https://togithub.com/spring-projects/spring-boot/issues/21760)
-   Document support for Gradle 5 [#&#8203;21752](https://togithub.com/spring-projects/spring-boot/issues/21752)
-   Replace whitelist with a term that does not have racist connotations [#&#8203;21744](https://togithub.com/spring-projects/spring-boot/issues/21744)
-   Polish [#&#8203;21732](https://togithub.com/spring-projects/spring-boot/pull/21732)
-   Use highlightjs for syntax highlighting in HTML documentation [#&#8203;21701](https://togithub.com/spring-projects/spring-boot/issues/21701)
-   Document deprecations of org.springframework.boot.loader.archive.Archive.iterator() [#&#8203;21695](https://togithub.com/spring-projects/spring-boot/issues/21695)
-   Documentation refers to wrong name for AvailabilityChangeEvent [#&#8203;21692](https://togithub.com/spring-projects/spring-boot/pull/21692)
-   Add reference to rocketmq-spring-boot-starter [#&#8203;21653](https://togithub.com/spring-projects/spring-boot/pull/21653)
-   Change liveness-port to management-port [#&#8203;21650](https://togithub.com/spring-projects/spring-boot/pull/21650)
-   {gradle-project-version}, rather than the project's actual version, appears in the Gradle plugin's reference documentation [#&#8203;21640](https://togithub.com/spring-projects/spring-boot/issues/21640)
-   Version-specific content is missing from Gradle Plugin's reference documentation [#&#8203;21610](https://togithub.com/spring-projects/spring-boot/issues/21610)
-   Polish duration support javadoc [#&#8203;21579](https://togithub.com/spring-projects/spring-boot/pull/21579)
-   Mark new public API added to spring-boot-loader in 2.3 with [@&#8203;since](https://togithub.com/since) tags [#&#8203;21576](https://togithub.com/spring-projects/spring-boot/issues/21576)
-   Links to Apache camel starter are broken [#&#8203;21563](https://togithub.com/spring-projects/spring-boot/issues/21563)
-   Fix typo in coordinates of junit-vintage-engine [#&#8203;21529](https://togithub.com/spring-projects/spring-boot/issues/21529)
-   Document how to enable liveness and readiness probes outside of a Kubernetes environment [#&#8203;21505](https://togithub.com/spring-projects/spring-boot/issues/21505)
-   Update configuration property metadata to reflect that spring.data.jpa.repositories.bootstrap-mode now defaults to deferred [#&#8203;21492](https://togithub.com/spring-projects/spring-boot/pull/21492)
-   Add an example for setting a custom image name on the command line with Gradle [#&#8203;21490](https://togithub.com/spring-projects/spring-boot/pull/21490)
-   Use https to link to groovy-lang.org [#&#8203;21472](https://togithub.com/spring-projects/spring-boot/issues/21472)

#### :hammer: Dependency Upgrades

-   Upgrade to Postgresql 42.2.14 [#&#8203;21871](https://togithub.com/spring-projects/spring-boot/issues/21871)
-   Upgrade to Netty tcNative 2.0.31.Final [#&#8203;21870](https://togithub.com/spring-projects/spring-boot/issues/21870)
-   Upgrade to Undertow 2.1.3.Final [#&#8203;21865](https://togithub.com/spring-projects/spring-boot/issues/21865)
-   Upgrade to Tomcat 9.0.36 [#&#8203;21864](https://togithub.com/spring-projects/spring-boot/issues/21864)
-   Upgrade to Spring Security 5.3.3.RELEASE [#&#8203;21863](https://togithub.com/spring-projects/spring-boot/issues/21863)
-   Upgrade to Spring AMQP 2.2.7.RELEASE [#&#8203;21862](https://togithub.com/spring-projects/spring-boot/issues/21862)
-   Upgrade to RSocket 1.0.1 [#&#8203;21861](https://togithub.com/spring-projects/spring-boot/issues/21861)
-   Upgrade to R2DBC Bom Arabba-SR4 [#&#8203;21860](https://togithub.com/spring-projects/spring-boot/issues/21860)
-   Upgrade to OkHttp3 3.14.9 [#&#8203;21858](https://togithub.com/spring-projects/spring-boot/issues/21858)
-   Upgrade to Netty 4.1.50.Final [#&#8203;21857](https://togithub.com/spring-projects/spring-boot/issues/21857)
-   Upgrade to Neo4j OGM 3.2.12 [#&#8203;21856](https://togithub.com/spring-projects/spring-boot/issues/21856)
-   Upgrade to MongoDB 4.0.4 [#&#8203;21855](https://togithub.com/spring-projects/spring-boot/issues/21855)
-   Upgrade to Log4j2 2.13.3 [#&#8203;21854](https://togithub.com/spring-projects/spring-boot/issues/21854)
-   Upgrade to Lettuce 5.3.1.RELEASE [#&#8203;21853](https://togithub.com/spring-projects/spring-boot/issues/21853)
-   Upgrade to Kotlin Coroutines 1.3.7 [#&#8203;21852](https://togithub.com/spring-projects/spring-boot/issues/21852)
-   Upgrade to Johnzon 1.2.7 [#&#8203;21851](https://togithub.com/spring-projects/spring-boot/issues/21851)
-   Upgrade to Jetty 9.4.29.v20200521 [#&#8203;21850](https://togithub.com/spring-projects/spring-boot/issues/21850)
-   Upgrade to Jetty Reactive HTTPClient 1.1.3 [#&#8203;21849](https://togithub.com/spring-projects/spring-boot/issues/21849)
-   Upgrade to Jaybird 3.0.9 [#&#8203;21848](https://togithub.com/spring-projects/spring-boot/issues/21848)
-   Upgrade to Hibernate 5.4.17.Final [#&#8203;21847](https://togithub.com/spring-projects/spring-boot/issues/21847)
-   Upgrade to Groovy 2.5.12 [#&#8203;21846](https://togithub.com/spring-projects/spring-boot/issues/21846)
-   Upgrade to Flyway 6.4.4 [#&#8203;21845](https://togithub.com/spring-projects/spring-boot/issues/21845)
-   Upgrade to Dropwizard Metrics 4.1.9 [#&#8203;21844](https://togithub.com/spring-projects/spring-boot/issues/21844)
-   Upgrade to Couchbase Client 3.0.5 [#&#8203;21843](https://togithub.com/spring-projects/spring-boot/issues/21843)
-   Upgrade to Caffeine 2.8.4 [#&#8203;21842](https://togithub.com/spring-projects/spring-boot/issues/21842)
-   Upgrade to Byte Buddy 1.10.11 [#&#8203;21841](https://togithub.com/spring-projects/spring-boot/issues/21841)
-   Upgrade to Awaitility 4.0.3 [#&#8203;21840](https://togithub.com/spring-projects/spring-boot/issues/21840)
-   Upgrade to Spring Batch 4.2.4 [#&#8203;21784](https://togithub.com/spring-projects/spring-boot/issues/21784)
-   Upgrade to Spring Kafka 2.5.2 [#&#8203;21782](https://togithub.com/spring-projects/spring-boot/issues/21782)
-   Upgrade to Spring Integration 5.3.1 [#&#8203;21779](https://togithub.com/spring-projects/spring-boot/issues/21779)
-   Upgrade to Spring Data Neumann-SR1 [#&#8203;21776](https://togithub.com/spring-projects/spring-boot/issues/21776)
-   Upgrade to Spring Framework 5.2.7 [#&#8203;21739](https://togithub.com/spring-projects/spring-boot/issues/21739)
-   Upgrade to Reactor Dysprosium-SR8 [#&#8203;21731](https://togithub.com/spring-projects/spring-boot/issues/21731)
-   Upgrade to Testcontainers 1.14.2 [#&#8203;21581](https://togithub.com/spring-projects/spring-boot/pull/21581)

#### :heart: Contributors

We'd like to thank all the contributors who worked on this release!

-   [@&#8203;ThierrySquirrel](https://togithub.com/ThierrySquirrel)
-   [@&#8203;OrangeDog](https://togithub.com/OrangeDog)
-   [@&#8203;dreis2211](https://togithub.com/dreis2211)
-   [@&#8203;evgeniycheban](https://togithub.com/evgeniycheban)
-   [@&#8203;fastso](https://togithub.com/fastso)
-   [@&#8203;wonwoo](https://togithub.com/wonwoo)
-   [@&#8203;encircled](https://togithub.com/encircled)
-   [@&#8203;tszmytka](https://togithub.com/tszmytka)
-   [@&#8203;Aurdo](https://togithub.com/Aurdo)
-   [@&#8203;making](https://togithub.com/making)
-   [@&#8203;dsyer](https://togithub.com/dsyer)

</details>

---

### Renovate configuration

:date: **Schedule**: At any time (no schedule defined).

:vertical_traffic_light: **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

:recycle: **Rebasing**: Never, or you tick the rebase/retry checkbox.

:no_bell: **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR has been generated by [WhiteSource Renovate](https://renovate.whitesourcesoftware.com). View repository job log [here](https://app.renovatebot.com/dashboard#GoogleCloudPlatform/getting-started-java).