Update reference from Debian 8 to Debian 9
Debian 8 is apparently no longer available. Consequently, the script fails with:
ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - The resource 'projects/debian-cloud/global/images/family/debian-8' was not found

This change resolves the error.